### ISSUE TITLE
Video image is not hiding after player starts

### ISSUE THREAD

**Issue by BartoszJarocki** [kaltura/player-sdk-native-android#101]
Version used:  **v2.3.0.rc4**
Environment: **Nexus 5, Android 6.0.1**
Steps to reproduce: **start player**

Video image will be hidden only after clicking player surface or rotating the device.
It's working ok on previous Android versions (4.2, 4.3)

**Comment by kaltura-hooks** [comment]
Hi @BartoszJarocki,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by noamtamim** [comment]
Please test with v2.4.0.rc1 and MWE v2.40.
What do you mean by video image?

**Comment by BartoszJarocki** [comment]
Image which is showing while video is loading.

**Comment by BartoszJarocki** [comment]
Same with v2.4.0.rc1.

**Comment by giladna** [comment]
Hi @BartoszJarocki 

Need more info in order to help
do you use auto play in your config?
can you change your player version to v2.5.16 and run the BasicPayerDemo with your config and share your findings?

**Comment by noamtamim** [comment]
This SDK is not supported anymore, you'll have to migrate to [PlayKit](https://kaltura.github.io/playkit/).
