### ISSUE TITLE
Test hook fix

### ISSUE THREAD

**Issue by jessport1** [kaltura/player-sdk-native-android#104]
Please do not close this for a while. Testing to make sure the auto reply only happens once.

**Comment by kaltura-hooks** [comment]
Hi @jessport1,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by jessport1** [comment]
Good - only posted auto message once. closing.
