### ISSUE TITLE
Repeaded calls on player play/pause methods causes unintentional advance in played resouce

### ISSUE THREAD

**Issue by Nahueleti** [kaltura/player-sdk-native-android#109]
Steps to reproduce:

1.- Play a resource with kaltura android player
2.- Repeatedly tap on play/pause button
3.- You will notice the playback progress and resource position to increase far beyond what the actual playback time would require

**Comment by kaltura-hooks** [comment]
Hi @Nahueleti,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by itaykinnrot** [comment]
Fixed in our latest version - please use v2.42+ (web player)
