### ISSUE TITLE
Closed caption frozen after pause/restart the player

### ISSUE THREAD

**Issue by filipecosta01** [kaltura/player-sdk-native-android#156]
The steps to reproduce it:
1- Play any video with closed caption enabled;
2- Press home button (the video will stop playing);
3- Go back to the app in which the video has been playing (it will start loading and playing again)
4- The closed caption will not be displayed or will be frozen (either one or another).
Disabling and enabling the closed caption won't make it work again.

**Comment by kaltura-hooks** [comment]
Hi @filipecosta01,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by itaykinnrot** [comment]
Can you please add the configuration?

**Comment by giladna** [comment]
Hi @filipecosta01 
We have changed the way we do the caption is selected please
give it a try on the 2.5.16 vesion
