### ISSUE TITLE
Player Seek

### ISSUE THREAD

**Issue by hrskrs** [kaltura/player-sdk-native-android#160]
I am using Kaltura SDK android v.2.5.4 and it works fine. However i wonder if i can seek to a specific video position. I couldnt find any doc about it. Tried some random like below but it wont work:
 `mPlayerView.sendNotification("doSeek", "300");`

How can i achieve that?

**Comment by kaltura-hooks** [comment]
Hi @hrskrs,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!
