### ISSUE TITLE
HOWTO: SDK integration as compiled version

### ISSUE THREAD

**Issue by qstuff** [kaltura/player-sdk-native-android#166]
I was looking for an integration solution that worked without having the repository cloned to the same working directory. I need to run automated builds on a CI and also need some version control.

It's possible using jitpack. Add following to your app/build.gradle:

```
dependencies {
    compile 'com.github.kaltura.player-sdk-native-android:playerSDK:v2.5.4'
    compile 'com.github.kaltura.player-sdk-native-android:googlemediaframework:v2.5.4'
}
```

and this in your root level build.gradle:

```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
```

Maybe you can add this to your README

**Comment by kaltura-hooks** [comment]
Hi @qstuff,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by jessp01** [comment]
Hi @qstuff,

Can you please submit a pull request?
This way we can properly credit you.

Thanks,

**Comment by qstuff** [comment]
sure will do so.
how is your policy on PRs ? creating a "feature/<meaningful_name>" branch from develop ?
and your latest stable version is 2.5.4, right.
thanks

**Comment by noamtamim** [comment]
@qstuff, yes on all of your questions -- 
- create a `feature/meaningful_name` branch from `develop`
- our latest stable release is 2.5.4

**Comment by qstuff** [comment]
@noamtamim ok pull request ist done

**Comment by qstuff** [comment]
i don't want to sign anything for contributing some lines of documentaion. it's outdated in the meantime anyway. you need to update the version number or add a placeholder. feel free to take it, i don't mind. thnaks & good luck
