### ISSUE TITLE
NullPointerException thrown from PlayerViewController.removeKPlayerEventListener

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-native-android#167]
Hi,

I'm using v2.5.4 of the player-sdk-native-android.

Would it be possible to put a check inside of PlayerViewController.removeKPlayerEventListener for when mPlayerEventsHash is NULL? This can happen if removeKPlayerEventListener is called without previously calling addKPlayerEventListener. 

Calling removeKPlayerEventListener without having previously called addKPlayerEventListener causes a NullPointerException to be thrown.

Thank you.

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
Hi @jabberdabber 
Thanks for your comment
This issue has been fixed already in 2.5.16 which you can download
You will be able to see that we have deprecated the old behaviour and split the listeners 
so you have to register only to the one that you are interested in
you can see this in example in the BasicPlayerDemo in 2.5.16
