### ISSUE TITLE
stretching the video inside the player

### ISSUE THREAD

**Issue by orenk86** [kaltura/player-sdk-native-android#203]
Hi,

We would like to be able to stretch and/or change the size of the video inside the player. With or without keeping the aspect ratio (doesn't matter at this point).

Is there a way to do this?

Thanks!

**Comment by kaltura-hooks** [comment]
Hi @orenk86,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by noamtamim** [comment]
This SDK is not supported anymore, you'll have to migrate to [PlayKit](https://kaltura.github.io/playkit/).
