### ISSUE TITLE
Pause after replay via native call

### ISSUE THREAD

**Issue by imrimarmor** [kaltura/player-sdk-native-android#265]
After a video ends, If I call `kalturaVideoPlayer.getMediaControl().replay();` the video will restart and immediately pause.
I'm seeing the same behaviour in your sdk semo project (hitting replay after video end in the BasicPlayerDemo app). 

Tested on an LG-G4 and Nexus 5, with player version 2.46 (2.47 and 2.48 aren't behaving any better).

**Comment by kaltura-hooks** [comment]
Hi @imrimarmor,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
@imrimarmor 
Please check if you add kalturaVideoPlayer.getMediaControl().start();

right after replay help you
if yes please update me
and I will update the native replay

Thanks

**Comment by imrimarmor** [comment]
@giladna Hi, I tried many variations on this logic (calling start() right after replay, calling after a slight delay, seeking to 0.1 and then start instead of calling replay) - but whatever I do I seem to be paused without a user interaction. 
You can recreate the issue on the sdk demos project.

**Comment by giladna** [comment]
@imrimarmor 
Which SDK version do you use?

**Comment by imrimarmor** [comment]
2.5.17.0

**Comment by giladna** [comment]
please upgrade to 2.5.28 
https://github.com/kaltura/player-sdk-native-android/releases/tag/v2.5.28

and try that start after replay

what is your partner and uiconf?

**Comment by imrimarmor** [comment]
Partner: 777882
uiconf: 34580511

**Comment by giladna** [comment]
@imrimarmor 
Thanks 
please update if fixed after upgrade

**Comment by giladna** [comment]
Fixed in:
https://github.com/kaltura/player-sdk-native-android/pull/266

Will be merged to develop by tomorrow probably
and in 2.5.29 release

**Comment by imrimarmor** [comment]
@giladna Works! Still have to call start() right after replay (otherwise I'm getting a frozen first frame with the audio running underneath), but still, works.
