### ISSUE TITLE
No source Video was found

### ISSUE THREAD

**Issue by codeteo** [kaltura/player-sdk-native-android#270]
I'm using kaltura SaaS to store videos but on some videos I'm getting : 

`   "no source video was found"
`

Is this an issue with kaltura player  ? 

Kaltura SDK version: '2.5.17.0'
Android device : Nexus 5X
Android version : 6.0.1

I tried also using `inlinePlayerDemo` from `KalturaDemos` with these values : 

            KPPlayerConfig config = new KPPlayerConfig("http://www.kaltura.com", "35420611", "2092431").setEntryId("1_z1saaxiz");

You can see in the next image that I'm getting the same error 

![device-2016-09-18-232915](https://cloud.githubusercontent.com/assets/4456512/18618858/0a426a04-7df8-11e6-8989-20219a729584.png)

Please let me know if you need more info.

**Comment by kaltura-hooks** [comment]
Hi @codeteo,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by codeteo** [comment]
OK I solve it. Host is `http://cdnapi.kaltura.com` and not `http://kaltura.com`.
