### ISSUE TITLE
Resuming from no network

### ISSUE THREAD

**Issue by imrimarmor** [kaltura/player-sdk-native-android#271]
Hi guys,
I'm trying to handle correctly a flow where the player was initialized with an entryId, but there was no network.
It looks like the player fires events up to LOADED in this case, and the spinner remains on screen. fine.

Now when the network connection returns, how do I get the player to start?
calling resumePlayer() or getMediaControl().start() did not work. Also tried calling changeMedia for that same entryId. Nothing happens.

I'm using sdk version 2.5.29 and embedFrame v2.48.rc3.
uiconfid 34580511 and partner 777882.

Thanks, 
Imri

**Comment by kaltura-hooks** [comment]
Hi @imrimarmor,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
you can see network error handling 
inside the KaltuaDemos project

run the AdPlayerDemo it has network resume code there
