### ISSUE TITLE
Unable to play Kaltura videos.

### ISSUE THREAD

**Issue by gauravjain131** [kaltura/player-sdk-native-android#272]
Hi, I'm trying to integrate Kaltura player to enable playing Kaltura videos within our Android app. I'm trying out this url : http://cdnbakmi.kaltura.com/p/303932/sp/30393200/serveFlavor/flavorId/0_jv7h719f/name/0_jv7h719f.mp4

Code where I'm using Kaltura SDK has been attached.

Error I get is this :
`09-20 12:29:07.495 20277-21802/in.til.popkorn E/chromium: [ERROR:ffmpeg_demuxer.cc(365)] Format conversion failed.
09-20 12:29:07.505 20277-21802/in.til.popkorn E/chromium: [ERROR:ffmpeg_demuxer.cc(1510)] OnReadFrameDone result=-1094995529 IsMaxMemoryUsageReached=0
09-20 12:29:08.675 20277-21802/in.til.popkorn E/chromium: [ERROR:ffmpeg_demuxer.cc(365)] Format conversion failed.
09-20 12:29:08.675 20277-21802/in.til.popkorn E/chromium: [ERROR:ffmpeg_demuxer.cc(1510)] OnReadFrameDone result=-1094995529 IsMaxMemoryUsageReached=0
                                                          
                                                          
                                                          [ 09-20 12:29:08.685 20560:23347 E/         ]
                                                          not in avi mode`

I have almost no experience working with video players, codecs or media playback, so it's a bit difficult to exactly understand the problem. Hence, would request Kaltura devs to help me in this.
Also, I would like to know where should I add administrator secret for playing out Kaltura videos in app.

[VideoStoriesFragment.zip](https://github.com/kaltura/player-sdk-native-android/files/481811/VideoStoriesFragment.zip)

**Comment by kaltura-hooks** [comment]
Hi @gauravjain131,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
Hi

You have to use the KMC
you have the the and the API 
you have the the information

SDK does not play url only content from the KMC

this is example for what you need
            KPPlayerConfig config = new KPPlayerConfig("http://cdnbakmi.kaltura.com", "35337951", "303932").setEntryId("0_lhifcwu4");



for example
