### ISSUE TITLE
webservice and parsing response creates lag

### ISSUE THREAD

**Issue by kanishR** [kaltura/player-sdk-native-android#279]
Hi,I am new to kaltura integrated demoApplication and wrote code i am using kaltura client library to make network calls and fetching response but it's not desired (As am loading data into viewpager) i am little bewildered why kaltura still using Xml response and Xml parsing and making network calls in asynctask.I couldn't find the scope to use retrofit and Rx for network . Could you guys help or tel me the correct way of using kaltura Sdk if m not heading in correct way

**Comment by kaltura-hooks** [comment]
Hi @kanishR,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
@kanishR 
I am not sure I understand which demo you are using
please attach a link to the code you work with.

@jessp01 
Do you have idea?

thanks

**Comment by jessp01** [comment]
Don't know which demo we're talking about but I'm sure @kanishR will provide a link.
@kanishR, in general, the Kaltura API is RESTful and so, the calls are stateless and made over HTTP[s]. In recent versions, you can decide whether to get the response back as XML or a JSON.

**Comment by kanishR** [comment]
Hi all ,Thanks for responding.
Maybe i should not report it as bug but i wanted to open the issue on performance ground 
I used this:
https://github.com/kaltura/player-sdk-native-android
to integrate kaltura SDK with my project
and followed this
https://knowledge.kaltura.com/kaltura-player-sdk-android

Now i did all well and my app has been developed but it has serious lag issues:\
Let me draw over all picture of development:
I have kaltura client library for network calls  integrated in my project and player sdk for streaming
since kaltura client library uses http client i need to make network calls in asynctask ..this is where lag comes .i want retrofit to manage my calls but since it is session based i can't use okhttp based libraries .
 here is my attached workspace.
![kalturaworkspace](https://cloud.githubusercontent.com/assets/22367518/18823679/d3b1d8fc-83d9-11e6-9a38-34dd61ae0d5c.png)

 Please suggest/advice or help for correct pathway to use kaltura sdk in intelligent way . Also  let me know if you guys want me to close iisue or move to another platform for discussion/improvment of kaltura sdk

**Comment by giladna** [comment]
@itaykinnrot 
This is BE issue  as far as I understand who do you think can help here?
Thanks
