### ISSUE TITLE
Player Loading Time

### ISSUE THREAD

**Issue by priteshtwr** [kaltura/player-sdk-native-android#286]
Hi ,
The player loading time is very poor.Its taken approx more than 5 seconds to load the video.
Is there any optimization that can be done or any work around ?

**Comment by kaltura-hooks** [comment]
Hi @priteshtwr,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
Hi

in v2.6.0
there is option to call 
PlayerViewController.prefetchPlayerResources(prefetchConfig, this);

the config should not have entry_id in this phase

this should optimize the first load 

please update if helps
