### ISSUE TITLE
Failed to resolve dependencies

### ISSUE THREAD

**Issue by joelclaudio** [kaltura/player-sdk-native-android#303]
I had a problem while adding the PlayerSDK library into our project. I was getting "Failed to resolve" while compiling com.google.ads.interactivemedia.v3 and com.googlecode.android-query on playerSDK.gradle.

My fix was to add the following to playerSDK.gradle:

```
repositories{
    mavenCentral()
    jcenter()
}
```
Is there any way for resolving this? Am I doing something wrong?

One option would be to include this in future versions so that others don't have the same problems as I did.

**Comment by kaltura-hooks** [comment]
Hi @joelclaudio,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!
