### ISSUE TITLE
Widevine Classic is not supported- Android 

### ISSUE THREAD

**Issue by danieltabarest** [kaltura/player-sdk-native-android#307]
I am using the Android 6.0 and the sdk is returning the following issue,

Java.Lang.UnsupportedOperationException: Widevine Classic is not supported
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()

it may not support Widevine in new versions of android, how can I solve this?

**Comment by kaltura-hooks** [comment]
Hi @danieltabarest,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
@danieltabarest 
you have to use dash instead this is the format recommanded for android 4.3 and up

**Comment by noamtamim** [comment]
This SDK is not supported anymore, you'll have to migrate to [PlayKit](https://kaltura.github.io/playkit/).
