### ISSUE TITLE
How to use Widevine DRM support

### ISSUE THREAD

**Issue by Spettacolo83** [kaltura/player-sdk-native-android#309]
Hello there,
it is written in the README.md that the player-sdk-native-android support Widevine DRM.
Can you provide an example on how to implement it?
It seems there is not examples in KalturaDemos directory regarding this.
Thank you!

**Comment by kaltura-hooks** [comment]
Hi @Spettacolo83,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by noamtamim** [comment]
This SDK is not supported anymore, you'll have to migrate to [PlayKit](https://kaltura.github.io/playkit/).
