### ISSUE TITLE
More than one file was found with OS independent path 'jsr305_annotations/Jsr305_annotations.gwt.xml'

### ISSUE THREAD

**Issue by omkarhande** [kaltura/player-sdk-native-android#310]
More than one file was found with OS independent path 'jsr305_annotations/Jsr305_annotations.gwt.xml'

**Comment by kaltura-hooks** [comment]
Hi @omkarhande,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by noamtamim** [comment]
This SDK is not supported anymore, you'll have to migrate to [PlayKit](https://kaltura.github.io/playkit/).
