### ISSUE TITLE
migration to new AndroidX support library standard

### ISSUE THREAD

**Issue by ChannVincent** [kaltura/player-sdk-native-android#312]
Hi!
Do you plan to migrate to the new AndroidX support?
If yes, do you have a release date?

Thank you

**Comment by kaltura-hooks** [comment]
Hi @ChannVincent,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
@ChannVincent 

we have new Playkit Version where we support Android x
https://github.com/kaltura/kaltura-player-android-samples/tree/master
