### ISSUE TITLE
Player time position

### ISSUE THREAD

**Issue by orenk86** [kaltura/player-sdk-native-android#57]
Hello,
I have implemented the player pretty much exactly like your example and it works great.
But for some reason, when switching to fullscreen and back, the player stops, reloads, and starts the video from the beginning.

This is pretty annoying, especially in long videos or when there's an preroll before the video (it plays the preroll again as well).
Any chance there's a way of preventing this? Having the video just keep playing is ideal, but a pause-reload-resume from current position will also be fine.

And another question, I tried to use the "addKPlayerEventListener" method to register for "timeupdate" events and it seems to work, but the "body" object is always null... Any way of fixing this?

Thanks!!

**Comment by kaltura-hooks** [comment]
Hi @orenk86,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by nissopa** [comment]
Hi,

Thanks for the notification, I will fix this issue and I will update you when it's ready

**Comment by orenk86** [comment]
Hi @nissopa , any news on this?

**Comment by kaltura-hooks** [comment]
Hi @orenk86,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by giladna** [comment]
Hi @orenk86 

We have made many changes since.

please take 2.5.16 and see in the BasicPlayerDemo example how to deal with the app lifecycle from the player point of view

**Comment by orenk86** [comment]
Thanks @giladna ,
Was the issue mentioned here addressed and solved?
