### ISSUE TITLE
Incorrect handle of device rotating

### ISSUE THREAD

**Issue by CAMOBAP795** [kaltura/player-sdk-native-android#75]
#### Problem

I noticed the problem related to device orientation changes, the video in landscape mode doesn't fill full available space, Example how it looks like on my device:

<img src="https://cloud.githubusercontent.com/assets/2169738/11498702/24a614ba-9832-11e5-91cb-79460fc7b7f9.png" data-canonical-src="https://cloud.githubusercontent.com/assets/2169738/11498702/24a614ba-9832-11e5-91cb-79460fc7b7f9.png" width="135" height="240" />

<img src="https://cloud.githubusercontent.com/assets/2169738/11498703/24a77972-9832-11e5-9618-db20ec89b08c.png" data-canonical-src="https://cloud.githubusercontent.com/assets/2169738/11498703/24a77972-9832-11e5-9618-db20ec89b08c.png" width="240" height="135" />

I have used official example `kalturaPlay` from this repo.

Device:
Sony Z3 Dual, OS: `Android 5.1.1`

Could you please help me with this?

#### Possible workarounds

1. Remove `orientation` from `/manifest/activity/android:configChanges`

  **Disadvantage**:
  -  2-4 sec delay after rotation, cursor position always dropped to 0
2. Initially set videoPlayer size to landscape, update `FullscreenFragment.showPlayerView()`

   ```
    public void showPlayerView() {
        getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);
        mPlayerView.setVisibility(RelativeLayout.VISIBLE);
        Point size = new Point();
        getActivity().getWindowManager().getDefaultDisplay().getSize(size);

        // workaround for portrait
        if (size.x < size.y) {
            size.x = size.x ^ size.y;
            size.y = size.x ^ size.y;
            size.x = size.x ^ size.y;
        }

        mPlayerView.setPlayerViewDimensions(size.x, size.y, 0, 0);
    }
    ```
  **Disadvantage**:
  - almost good, but first 2-3 sec, players looks bad then it automatically refreshed and looks ok

     <img src="https://cloud.githubusercontent.com/assets/2169738/11499254/c366b6e2-9835-11e5-9128-f0ed67e05353.png" data-canonical-src="https://cloud.githubusercontent.com/assets/2169738/11499254/c366b6e2-9835-11e5-9128-f0ed67e05353.png" width="135" height="240" />

3. Make `Activity` landscape only in manifest, if this acceptable

**Comment by kaltura-hooks** [comment]
Hi @CAMOBAP795,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by itaykinnrot** [comment]
Please check our demo app.
Thanks,
