### ISSUE TITLE
Test hook

### ISSUE THREAD

**Issue by jessport1** [kaltura/player-sdk-native-android#93]

**Comment by kaltura-hooks** [comment]
Hi @jessport1,

Hi @jessport1,


Thank for you reporting an issue and helping improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue and post at:
https://forum.kaltura.org/c/community-forums/player-sdk


Thank you in advance!
