### ISSUE TITLE
No vdeo, only sound

### ISSUE THREAD

**Issue by Arthurius** [kaltura/player-sdk-native-android#95]
Hello,

I'm trying to write a CoronaSDK plugin using the Kaltura player. I've managed to load the player and load a video, but I only see the controls and hear the sound. 

I use this code to add Kaltura to Corona:

`public int show(LuaState L) {+
        // Fetch a reference to the Corona activity.
        // Note: Will be null if the end-user has just backed out of the activity.
        CoronaActivity activity = CoronaEnvironment.getCoronaActivity();
        if (activity == null) {
            return 0;
        }
        // Fetch the first argument from the called Lua function.
        String the_id = L.checkString( 1 );
        if ( null == the_id ) {
            the_id = "1_sf5ovm7u";
        }
        // Create web view on the main UI thread.
        if (activity != null) {
            final String video_id =  the_id;
            activity.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    // Fetch a reference to the Corona activity.
                    // Note: Will be null if the end-user has just backed out of the activity.
                    CoronaActivity activity = CoronaEnvironment.getCoronaActivity();
                    if (activity == null) {
                        return;
                    }
                    if ( null == mPlayerView ) {
                        mPlayerView = new PlayerViewController(activity);
                        mPlayerView.loadPlayerIntoActivity(activity);
                        CoronaEnvironment.getCoronaActivity().getOverlayView().addView( mPlayerView );
                    }
                    KPPlayerConfig config = new KPPlayerConfig("http://cdnapi.kaltura.com", "29030452", "1868701");
                    config.setEntryId(video_id);
                    mPlayerView.initWithConfiguration(config);
                }
            } );
        }
        return 0;
    }`

What am I missing here?
Thanks, 
Arthur Schenk

**Comment by kaltura-hooks** [comment]
Hi @Arthurius,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue and post at:
https://forum.kaltura.org/c/community-forums/player-sdk


Thank you in advance!

**Comment by Arthurius** [comment]
Ok, thanks
