### ISSUE TITLE
Need to programatically change the watermark

### ISSUE THREAD

**Issue by Nahueleti** [kaltura/player-sdk-native-android#97]
Hello Kaltura support, we have the need to change the entitlement's watermark to match the user's full name. We haven't found any reference to how to do it in you docs or API docs, http://player.kaltura.com/docs/api

Can you please advice?

**Comment by kaltura-hooks** [comment]
Hi @Nahueleti,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by kaltura-hooks** [comment]
Hi @Nahueleti,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by kaltura-hooks** [comment]
Hi @Nahueleti,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by jessp01** [comment]
Hi @Nahueleti,

I am not exactly sure what you mean by: "entitlement's watermark to match the user's full name."
The player watermark basically has these fields in the JSON:
"logo": {
                        "href": "",
                        "title": "",
                        "plugin": true,
                        "img": ""
},

href: where to the redirect the user when the image is clicked.
title: an alt/description tag when the mouse is over the image
img: where to load the image from

So, if what you want is to add the image creator's name, you can use the "title" for that.
If you meant something else, kindly explain exactly what in a forum post here:
https://forum.kaltura.org/c/community-forums/player-sdk

We'd rather keep the github issues section for bug reporting only and not for general questions.

Thanks,
